[build]
  command = "npm ci && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18.19.0"
  NPM_VERSION = "10.2.3"
  NPM_FLAGS = "--legacy-peer-deps --no-optional"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
